### ISSUE TITLE
Stream has already been listended to.

### ISSUE THREAD

**Issue by Sheikh12345** [uzairleo/easy_geofencing#5]

**Comment by JasminScalelot** [comment]
Same problem

**Comment by arifpermadi999** [comment]
same with me, how to resolve it?

**Comment by sujataagarwal** [comment]
Calling EasyGeofencing.getGeofenceStream() multiple times, from multiplaces gives this.

**Comment by uzairleo** [comment]
Hi there guys thanks for reporting the issue i am looking into this will sooner update this to null safety and also with the reported issues solution

**Comment by PiyushJagtap** [comment]
Made below changes in easy_geofencing.dart and it worked for me.
`static stopGeofenceService() {
    print(_positionStream);
    if (_positionStream != null) {
      _positionStream!.cancel();
      _positionStream = null;
    }
  }`

And when calling Geofence service and Geofence Stream multiple time, stop the geofence service and cancel the stream before changing the route.
`geofenceStatusStream?.cancel();
EasyGeofencing.stopGeofenceService();`

**Comment by shadid06** [comment]
> Made below changes in easy_geofencing.dart and it worked for me. `static stopGeofenceService() {` `print(_positionStream);` `f (_positionStream != null) {` `_positionStream!.cancel();` ` _positionStream = null;` ` }` `}`
> 
> And when calling Geofence service and Geofence Stream multiple time, stop the geofence service and cancel the stream before changing the route. `geofenceStatusStream?.cancel();` `EasyGeofencing.stopGeofenceService();`

i did what you told, but gives  Parse value===>false and fence service doesnt start

**Comment by Soliardi-Chyngyz** [comment]
Hello everyone, I will not be selfish and will share with you how I fixed it myself.

You should make changes to the library itself
version 0.2.0

_static stopGeofenceService() {
     if (_positionStream != null) {
       _positionStream!.cancel();
       _positionStream = null;
     }
   }_

_wherever there is an add function, add a sink
       _controller.sink.add(GeofenceStatus.enter);_

well, the most important thing is to add broadcast ()
static StreamController<GeofenceStatus> _controller =
       **StreamController<GeofenceStatus>.broadcast()**;

Well, now it's up to you, call stop() and start()
Since this is a stream, we don’t forget that the previous stream loses all data, there can always be only 1 stream, well, or correct me, thanks to Putler kaput, Ukraine wins
